version: '3.9'

services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
  isd_hackathon_backend:
    build: .
    container_name: isd_hackathon_backend
    restart: always
    ports:
      - ${PORT}:${PORT}
    links:
      - mysqldb
