version: '3.9'

services:
  mysqldb:
    image: mysql
    container_name: mysqldb
    volumes:
      - ./mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    links:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
      PMA_ARBITARY: 1
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
